packages:
  - apps/*
  - packages/*

catalog:
  '@floating-ui/vue': 1.1.10
  '@types/node': 24.7.2
  '@vitejs/plugin-vue': 6.0.4
  '@vue/test-utils': 2.4.6
  happy-dom: 20.6.1
  nuxt: 4.3.1
  oxlint: 1.48.0
  typescript: 5.9.3
  vite: 7.3.1
  vite-plugin-vue-devtools: 8.0.6
  vitepress: 1.6.4
  vitest: 3.1.4
  vue: 3.5.28
  vue-router: 5.0.2
  vue-tsc: 2.2.10

catalogMode: strict

catalogs:
  consumer:
    '@floating-ui/vue': ^1.1.0
    nuxt: ^4.3.1
    vue: ^3.5.0
    vue-router: ^4.0.0

overrides:
  '@vrgl/vergil>@floating-ui/vue': 'catalog:'
  '@vrgl/vergil>nuxt': 'catalog:'
  '@vrgl/vergil>vue': 'catalog:'
  '@vrgl/vergil>vue-router': 'catalog:'
