packages:
  - apps/*
  - packages/*

catalog:
  '@floating-ui/vue': 1.1.9
  '@types/node': 24.7.2
  '@vitejs/plugin-vue': 6.0.1
  '@vue/test-utils': 2.4.6
  happy-dom: 20.0.2
  nuxt: 4.2.0
  oxlint: 1.23.0
  typescript: 5.9.3
  vite: 6.3.5
  vite-plugin-vue-devtools: 8.0.5
  vitepress: 1.6.4
  vitest: 3.1.4
  vue: 3.5.16
  vue-router: 4.5.1
  vue-tsc: 2.2.10

catalogMode: strict

catalogs:
  consumer:
    '@floating-ui/vue': ^1.1.0
    nuxt: ^4.0.0
    vue: ^3.5.0
    vue-router: ^4.0.0

overrides:
  '@8ctavio/vergil>@floating-ui/vue': 'catalog:'
  '@8ctavio/vergil>nuxt': 'catalog:'
  '@8ctavio/vergil>vue': 'catalog:'
  '@8ctavio/vergil>vue-router': 'catalog:'
