packages:
  - apps/*
  - packages/*

catalog:
  '@floating-ui/vue': 1.1.9
  '@types/node': 24.7.1
  '@vitejs/plugin-vue': 5.2.4
  '@vue/test-utils': 2.4.6
  happy-dom: 20.0.0
  oxlint: 1.22.0
  typescript: 5.9.3
  vite: 6.3.5
  vitepress: 1.6.4
  vitest: 3.1.4
  vue: 3.5.16
  vue-tsc: 2.2.10

catalogMode: strict

catalogs:
  consumer:
    '@floating-ui/vue': ^1.1.0
    vue: ^3.5.0

overrides:
  '@8ctavio/vergil>@floating-ui/vue': 'catalog:'
  '@8ctavio/vergil>vue': 'catalog:'
