packages:
  - apps/*
  - packages/*

dedupePeers: true
catalogMode: strict

catalog:
  '@floating-ui/vue': 1.1.11
  '@types/node': 25.8.0
  '@vitejs/plugin-vue': 6.0.7
  '@vue/test-utils': 2.4.10
  happy-dom: 20.9.0
  nuxt: 4.4.5
  oxlint: 1.65.0
  typescript: 6.0.3
  vite: 7.3.2
  vite-plugin-vue-devtools: 8.1.2
  vitepress: 2.0.0-alpha.16
  vitepress-plugin-group-icons: 1.7.5
  vitest: 4.1.6
  vue: 3.5.34
  vue-router: 5.0.7
  vue-tsc: 3.2.9

catalogs:
  consumer:
    '@floating-ui/vue': ^1.1.0
    nuxt: ^4.3.1
    vue: ^3.5.0
    vue-router: ^4.0.0

overrides:
  '@vrgl/vergil>@floating-ui/vue': 'catalog:'
  '@vrgl/vergil>nuxt': 'catalog:'
  '@vrgl/vergil>vue': 'catalog:'
  '@vrgl/vergil>vue-router': 'catalog:'

allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  vue-demi: false