name: ci

on:
  pull_request:
    branches: [main]
    paths: ['packages/core/**']
  push:
    branches: [main]
    paths: ['packages/core/**']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm lint
      - name: Generate declaration files
        run: pnpm --filter vergil dts
      - name: Run tests
        run: pnpm --filter vergil test:prod